const IS_LOGGED_IN = 'IS_LOGGED_IN';
const USER_TOKEN = 'USER_TOKEN';
const IS_COMPLETE_ON_BOARDING = 'IS_COMPLETE_ON_BOARDING';
const IS_STORE_GCM_TOKEN = 'IS_STORE_GCM_TOKEN';
const USER_TIMEZONE = 'USER_TIMEZONE';
const LOGIN_CREDENTIALS = 'LOGIN_CREDENTIALS';
const TEAM_USERS = 'TEAM_USERS';
const USER_LEAD_SOURCE = 'USER_LEAD_SOURCE';
const USER_VIRTUAL_NUMBER = 'USER_VIRTUAL_NUMBER';
const USER_CUSTOM_FIELD = 'USER_CUSTOM_FIELD';
const USER_STANDARD_PERSONALIZED_FIELD = 'USER_STANDARD_PERSONALIZED_FIELD';

export {
  IS_LOGGED_IN,
  USER_TOKEN,
  IS_COMPLETE_ON_BOARDING,
  IS_STORE_GCM_TOKEN,
  USER_TIMEZONE,
  LOGIN_CREDENTIALS,
  TEAM_USERS,
  USER_LEAD_SOURCE,
  USER_VIRTUAL_NUMBER,
  USER_CUSTOM_FIELD,
  USER_STANDARD_PERSONALIZED_FIELD,
};
